spring:
  datasource:
    url: jdbc:h2:mem:newsdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  h2:
    console:
      enabled: true
 
server:
  port: 8080
 
app:
  jwt:
    secret: dev-secret-change
    expirySeconds: 86400
  newsapi:
    key: YOUR_NEWSAPI_KEY_HERE
    sources: techcrunch,the-verge,bbc-news
    fetchCron: "0 */10 * * * *"